services:
  postgres:
    image: postgres:16
    container_name: classroom-db
    environment:
      POSTGRES_DB: classroom_reservation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - classroom-db-data:/var/lib/postgresql/data

volumes:
  classroom-db-data: